site_name: ClearAligner
site_description: ClearAligner is a cross-platform tool for working with alignment data.
site_url: https://clear-aligner-docs.netlify.app/
docs_dir: site-content
repo_url: https://github.com/Clear-Bible/clear-aligner

theme:
  name: shadcn
  icon: assets/logo-icon-large-light.png
  favicon: assets/logo-icon-small-light.png
  palette:
    primary: blue
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Features: features.md
  - Roadmap: roadmap.md
  - File Formats:
    - Target Text: file-formats/target-text.md
    - Alignment Data: file-formats/alignment-data.md
  - Releases:
    - "1.0.0": releases/1.0.0.md
    - "0.0.33": releases/0.0.33.md
    - "0.0.31": releases/0.0.31.md
    - "0.0.29": releases/0.0.29.md
    - "0.0.26": releases/0.0.26.md

markdown_extensions:
  - tables
  - fenced_code
  - codehilite
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
