name: Execute tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create yarn.lock
        run: touch yarn.lock
      - uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'yarn'
      - name: Perform linting
        run: |
          npm i -g eslint
          yarn install
          yarn lint
      - name: Configure environment
        run: |
          echo CA_AWS_ENDPOINT="${CA_AWS_ENDPOINT}">> .env
          echo CA_AWS_COGNITO_USER_POOL_ID="${CA_AWS_COGNITO_USER_POOL_ID}">> .env
          echo CA_AWS_COGNITO_USER_POOL_CLIENT_ID="${CA_AWS_COGNITO_USER_POOL_CLIENT_ID}">> .env
          echo CA_AWS_COGNITO_PERMANENT_PASSWORD_CREATION_URL="${CA_AWS_COGNITO_PERMANENT_PASSWORD_CREATION_URL}">> .env
        env:
          CA_AWS_ENDPOINT: ${{ secrets.CA_AWS_ENDPOINT }}
          CA_AWS_COGNITO_USER_POOL_ID: ${{ secrets.CA_AWS_COGNITO_USER_POOL_ID }}
          CA_AWS_COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.CA_AWS_COGNITO_USER_POOL_CLIENT_ID }}
          CA_AWS_COGNITO_PERMANENT_PASSWORD_CREATION_URL: ${{ secrets.CA_AWS_COGNITO_PERMANENT_PASSWORD_CREATION_URL }}
      - name: Run tests
        run: |
          yarn test-ui
          yarn test-electron

